#!/usr/bin/env sh

spacebar -m config position      top
spacebar -m config height       28 
spacebar -m config title         on
spacebar -m config spaces        on
spacebar -m config power         on
spacebar -m config clock         on
spacebar -m config padding_left      20
spacebar -m config padding_right         20
spacebar -m config spacing_left      25
spacebar -m config spacing_right        10 
spacebar -m config text_font         "FiraCode Nerd Font Mono:16.0"
spacebar -m config icon_font         "Font Awesome 5 Free:Solid:16.0"
spacebar -m config background_color      0xff181926
spacebar -m config foreground_color      0xffeebebe
spacebar -m config space_icon_color      0xffe64553
spacebar -m config space_icon_strip      i ii iii iv v vi vii viii ix x
spacebar -m config spaces_for_all_displays       on
spacebar -m config power_icon_strip     " " " " #
spacebar -m config display_separator         on
spacebar -m config display_separator_icon        |
spacebar -m config clock_format      "%a %d %H.%M"
spacebar -m config clock_icon           " "
spacebar -m config clock_icon_color      0xffeebebe

echo "spacebar configuration loaded.."

